# Capture live evidence from all three targets into EVIDENCE.md.
#
#   .\scripts\capture-evidence.ps1
#
# Everything in the generated file is read back from the workspace at run time,
# so it cannot drift from reality: re-run it and the numbers update.
#
# Style note: markdown containing backticks is written with SINGLE-quoted
# PowerShell strings. In a double-quoted string the backtick is the escape
# character, which silently corrupts the parse.
param(
    [string]$OutFile = 'EVIDENCE.md',
    [string]$Catalog = 'telematics'
)

$ErrorActionPreference = 'Stop'
$env:Path = [Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' +
            [Environment]::GetEnvironmentVariable('Path', 'User')

$root = Split-Path $PSScriptRoot -Parent
Set-Location $root

$lines = New-Object System.Collections.Generic.List[string]
function Add-Line($text) { $lines.Add([string]$text) }

function Add-Query($target, $sql) {
    $result = & "$root\scripts\query.ps1" -Target $target -Sql $sql -Catalog $Catalog
    Add-Line '```'
    Add-Line (($result | Out-String).TrimEnd())
    Add-Line '```'
    Add-Line ''
}

$fence = '```'
$stamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

Add-Line '# EVIDENCE - captured from the live workspace'
Add-Line ''
Add-Line "Generated by ``scripts/capture-evidence.ps1`` on $stamp local time."
Add-Line 'Every figure below is read back from Databricks at capture time, so it cannot'
Add-Line 'drift from what the workspace actually contains.'
Add-Line ''
Add-Line '> This is written corroboration. The screen recording or screenshots the brief'
Add-Line '> asks for still need to be captured from the workspace UI - see the checklist'
Add-Line '> at the end.'
Add-Line ''

Add-Line '## Deployed resources'
Add-Line ''
Add-Line $fence
foreach ($t in @('dev', 'test', 'prod')) {
    $s = databricks bundle summary -t $t --output json | Out-String | ConvertFrom-Json
    Add-Line "target $t"
    foreach ($p in $s.resources.jobs.PSObject.Properties) {
        Add-Line ("  job    {0,-16} id={1}" -f $p.Name, $p.Value.id)
    }
    Add-Line ("  schema {0}.{1}" -f $Catalog, $t)
}
Add-Line $fence
Add-Line ''

foreach ($t in @('dev', 'test', 'prod')) {
    Add-Line "## Target: $t"
    Add-Line ''

    Add-Line '### Row counts through the medallion'
    Add-Line ''
    Add-Query $t "SELECT 'bronze_pings_raw' AS tbl, count(*) AS rows FROM bronze_pings_raw UNION ALL SELECT 'silver_pings', count(*) FROM silver_pings UNION ALL SELECT 'silver_pings_quarantine', count(*) FROM silver_pings_quarantine UNION ALL SELECT 'truck_details', count(*) FROM truck_details UNION ALL SELECT 'gold_truck_current_position', count(*) FROM gold_truck_current_position UNION ALL SELECT 'gold_region_activity_5m', count(*) FROM gold_region_activity_5m ORDER BY tbl"

    Add-Line '### Deduplication - every Silver row has a distinct key'
    Add-Line ''
    Add-Query $t "SELECT count(*) AS silver_rows, count(DISTINCT ping_id) AS distinct_keys FROM silver_pings"

    Add-Line '### Quarantined rows - kept, not dropped'
    Add-Line ''
    Add-Query $t "SELECT reject_reason, count(*) AS rows FROM silver_pings_quarantine GROUP BY reject_reason ORDER BY rows DESC"

    Add-Line '### Gold - the stream-static join'
    Add-Line ''
    Add-Line 'The make, driver, home_depot and region columns exist only in the static'
    Add-Line 'truck_details dimension. Their presence here is the join.'
    Add-Line ''
    Add-Query $t "SELECT truck_id, last_event_ts, round(latitude, 4) AS lat, round(longitude, 4) AS lon, make, driver, home_depot, region FROM gold_truck_current_position ORDER BY truck_id LIMIT 5"

    Add-Line '### Gold - pings per region per 5-minute window'
    Add-Line ''
    Add-Query $t "SELECT region, window_start, ping_count, truck_count FROM gold_region_activity_5m ORDER BY window_start DESC, region LIMIT 8"

    Add-Line '### Migration ledger - how table structure reached this environment'
    Add-Line ''
    Add-Query $t "SELECT version, filename, applied_at, applied_by, statements FROM schema_migrations ORDER BY version"

    Add-Line '### The promoted column change (migration 002)'
    Add-Line ''
    Add-Query $t "SELECT column_name, data_type FROM information_schema.columns WHERE table_schema = '$t' AND table_name = 'gold_truck_current_position' AND column_name IN ('in_geofence', 'geofence_name') ORDER BY column_name"
    Add-Query $t "SELECT geofence_name, in_geofence, count(*) AS trucks FROM gold_truck_current_position GROUP BY geofence_name, in_geofence ORDER BY in_geofence DESC"
}

Add-Line '## Still to capture from the UI'
Add-Line ''
Add-Line 'The brief asks for a 3-5 minute recording or screenshots. This file covers the'
Add-Line 'data; the following need the workspace UI:'
Add-Line ''
Add-Line '- [ ] `databricks bundle deploy` succeeding for all three targets, in a terminal'
Add-Line '- [ ] the three job pairs in Workflows, showing their different names and schedules'
Add-Line '- [ ] a successful `medallion_job` run graph (migrations -> bronze -> silver -> gold)'
Add-Line '- [ ] `gold_truck_current_position` in the data explorer, with the joined columns'
Add-Line '- [ ] `DESCRIBE TABLE gold_truck_current_position` in prod, before and after migration 002'
Add-Line '- [ ] `SELECT * FROM schema_migrations` in prod, showing both versions and timestamps'

$path = Join-Path $root $OutFile
[System.IO.File]::WriteAllText($path, ($lines -join "`r`n") + "`r`n",
                               (New-Object System.Text.UTF8Encoding $false))
"wrote $OutFile"
